services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu", "utility", "compute" ]
              driver: nvidia
              count: 1
